language: python

jobs:
  include:
    - stage: core
      python:
        - "2.7"
        - "3.4"
        - "3.5"
        - "3.6"
        - "pypy"
      install:
        - pip install -r requirements.txt
      script:
        - nosetests -v
    - stage: beaker
      python:
      - "2.7"
      - "3.4"
      - "3.5"
      - "3.6"
      - "pypy"
      install:
        - pip install -e .[beaker]
      script:
        - nosetests -v

