language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

jobs:
  include:
    - stage: core
      install:
        - pip install -r requirements.txt
    - stage: beaker
      install:
        - pip install -e .[beaker]

script:
  - nosetests -v
